sudo: required

language: java

matrix:
  include:

    - env: DEPLOY='linux'
      jdk: openjdk11
      
    - env: DEPLOY='linux-12'
      jdk: openjdk12
      
    - env: DEPLOY='linux-13-early-access'
      jdk: openjdk13

