version: '1'
services:
 
  hw-mysql:
   container_name: hw-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: homework
    MYSQL_ROOT_PASSWORD: dbuser00
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - hw-mysql